version: '3'

services:
  web:
    container_name: car_v2_web
    image: nginx:1.19
    ports:
      - '81:80'
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./app:/app
    networks:
      - car-network

  node:
    build:
      context: .
      dockerfile: NODE.DOCKERFILE
    volumes:
      - ./appnode:/appnode
      - /appnode/node_modules
    ports:
      - 5002:5002
    networks:
      - car-network

  frontend:
    container_name: car_v2_react
    build:
      context: .
      dockerfile: FRONT.DOCKERFILE
    environment:
      WATCHPACK_POLLING: 'true'
    ports:
      - 3000:3000
    volumes:
      - ./appreact:/appreact
      - /appreact/node_modules
    networks:
      - car-network

  mysql:
    container_name: car_v2_mysql
    image: mariadb:10.7.3
    environment:
      MYSQL_ROOT_PASSWORD: 'admin'
      MYSQL_USER: 'admin'
      MYSQL_PASSWORD: 'admin'
      MYSQL_DATABASE: 'mydb'
    volumes:
      - mysqldata:/var/lib/mysql
    ports:
      - 3306:3306
    networks:
      - car-network

  mongodb:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - ./data/db:/data/db
      - ./init.js:/docker-entrypoint-initdb.d/init.js

    networks:
      - car-network

networks:
  car-network:
    driver: bridge

volumes:
  mysqldata: {}
